apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: assignment
  template:
    metadata:
      labels:
        app: assignment
    spec:
      containers:
      - name: assignmenet-container
        image: absolutracy/test-app:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"