apiVersion: v1  
kind: Service 
metadata: 
  name: assignment-service 
spec: 
  type: NodePort 
  selector: 
    app: assignment   
ports: 
- protocol: TCP 
  port: 8080 
  targetPort: 8000 
  nodePort: 60086